# Service for DuckDB
apiVersion: v1
kind: Service
metadata:
  name: duckdb
  namespace: liquidtables
spec:
  selector:
    app: duckdb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

---
# Service for FastAPI
apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: liquidtables
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: fastapi

---
# Service for Svelte
apiVersion: v1
kind: Service
metadata:
  name: svelte
  namespace: liquidtables
  labels:
    app: svelte
spec:
  type: LoadBalancer
  selector:
    app: svelte
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
